#define a CI/CD Pipeline using GitHub Actions
name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #check out code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python and install setuptools
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python -m pip install setuptools

      - name: Install dependencies
        run: python setup.py develop

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: ipshitadockerhub-image
        run: |
          python setup.py sdist bdist_wheel
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      #set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print Flask and Werkzeug versions
        run: |
          pip show Flask
          pip show Werkzeug

      - name: Install pytest
        run: pip install pytest

      - name: Run tests with pytest
        run: pytest tests.py


